export const ECUADOR_DATA: Record<string, string[]> = {
    "Azuay": ["Cuenca", "Gualaceo", "Paute", "Sigsig", "Girón", "Santa Isabel"],
    "Bolívar": ["Guaranda", "San Miguel", "Caluma", "Echeandía", "Chimbo"],
    "Cañar": ["Azogues", "Cañar", "La Troncal", "Biblián", "Deleg"],
    "Carchi": ["Tulcán", "Montúfar", "Espejo", "Mira", "Bolívar"],
    "Chimborazo": ["Riobamba", "Guano", "Colta", "Alausí", "Chunchi"],
    "Cotopaxi": ["Latacunga", "Pujilí", "Salcedo", "Saquisilí", "La Maná"],
    "El Oro": ["Machala", "Pasaje", "Santa Rosa", "Huaquillas", "Arenillas", "Piñas", "Zaruma"],
    "Esmeraldas": ["Esmeraldas", "Quinindé", "Atacames", "San Lorenzo", "Muisne"],
    "Galápagos": ["Puerto Baquerizo Moreno", "Puerto Ayora", "Puerto Villamil"],
    "Guayas": ["Guayaquil", "Durán", "Samborondón", "Milagro", "Daule", "Playas", "Balao", "Naranjal", "Salitre"],
    "Imbabura": ["Ibarra", "Otavalo", "Cotacachi", "Antonio Ante", "Pimampiro"],
    "Loja": ["Loja", "Catamayo", "Cariamanga", "Macará", "Saraguro", "Zapotillo"],
    "Los Ríos": ["Babahoyo", "Quevedo", "Ventanas", "Vinces", "Buena Fe", "Valencia", "Mocache"],
    "Manabí": ["Portoviejo", "Manta", "Chone", "Bahía de Caráquez", "Jipijapa", "Montecristi", "El Carmen", "Calceta"],
    "Morona Santiago": ["Macas", "Gualaquiza", "Sucúa", "Limón Indanza"],
    "Napo": ["Tena", "Archidona", "El Chaco", "Quijos"],
    "Orellana": ["Puerto Francisco de Orellana", "La Joya de los Sachas", "Loreto"],
    "Pastaza": ["Puyo", "Mera", "Santa Clara"],
    "Pichincha": ["Quito", "Sangolquí", "Machachi", "Cayambe", "Tabacundo", "Puerto Quito"],
    "Santa Elena": ["Santa Elena", "La Libertad", "Salinas"],
    "Santo Domingo de los Tsáchilas": ["Santo Domingo"],
    "Sucumbíos": ["Nueva Loja", "Shushufindi", "Cuyabeno"],
    "Tungurahua": ["Ambato", "Baños", "Pelileo", "Píllaro", "Quero"],
    "Zamora Chinchipe": ["Zamora", "Yantzaza", "El Pangui"]
};
